from langchain.llms import OpenAI
import os
import dotenv

dotenv.load_dotenv(dotenv.find_dotenv())

llm = OpenAI(openai_api_key=os.getenv("OPENAI_API_KEY"))

llm = OpenAI(temperature=0)


def search_links_lch(response):
    links = []
    response = response.split("\n")
    for i in response:
        query = llm.predict(f"give 1 link of free resource for each topic to learn {i} CHECK THAT ALLL SITES ARE WORKING ")
        links.append(query)
    return links


# response = """(1) Learn programming languages such as Python, Java, or Ruby. 
# (2) Learn databases such as MySQL, PostgreSQL, or MongoDB."""

# print(search_links_lch(response))

# links =['\n\n1. Python: https://www.codecademy.com/learn/learn-python\n2. Java: https://www.codecademy.com/learn/learn-java\n3. Ruby: https://www.codecademy.com/learn/learn-ruby', '\n\n1. MySQL: https://www.mysqltutorial.org/\n2. PostgreSQL: https://www.postgresqltutorial.com/\n3. MongoDB: https://university.mongodb.com/']

# a = ['\\n\\n1. C++ Tutorial for Beginners: 
# https://www.programiz.com/cpp-programming/tutorial', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\n1. Object-Oriented Programming (OOP):\\n\\n• Tutorials Point: https://www.tutorialspoint.com/object_oriented_programming/index.htm\\n\\n• W3Schools: https://www.w3schools.com/cpp/cpp_oop.asp\\n\\n• GeeksforGeeks: https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-cpp/\\n\\n• CodeProject: https://www.codeproject.com/Articles/22769/Introduction-to-Object-Oriented-Programming-Concep\\n\\n• Programiz: https://www.programiz.com/cpp-programming/object-oriented-programming', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\nhttps://www.programiz.com/cpp-programming/memory-management', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: 
# \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\n1. Standard Template Library (STL): https://www.learncpp.com/cpp-tutorial/the-standard-template-library-stl/', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\nhttps://www.programiz.com/cpp-programming/file-handling', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\n1. Multithreading and Concurrency: https://www.tutorialspoint.com/cplusplus/cpp_multithreading.htm', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\nhttps://www.tutorialspoint.com/cplusplus/cpp_networking.htm', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\nhttps://www.tutorialspoint.com/cplusplus_sqlite/index.htm', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\n1. Performance Optimization: https://www.tutorialspoint.com/cplusplus/cpp_performance_optimization.htm', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', 
# '\\n\\nDebugging: \\nhttps://www.learncpp.com/cpp-tutorial/debugging-with-gdb/\\n\\nTesting: \\nhttps://www.guru99.com/c-plus-plus-testing-framework.html', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', 
# '\\n\\nBuild Systems:\\nhttps://www.tutorialspoint.com/cmake/index.htm\\n\\nVersion Control:\\nhttps://www.atlassian.com/git/tutorials/what-is-version-control', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\n1. Wt Framework: https://www.webtoolkit.eu/wt\\n2. CppCMS: http://cppcms.com/\\n3. Handling HTTP Requests: https://www.tutorialspoint.com/http/http_requests.htm\\n4. Building APIs: https://www.codecademy.com/articles/what-is-an-api\\n5. Integrating with Frontend Technologies: https://www.tutorialspoint.com/front_end_web_development/index.htm', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\n1. Security in C++: https://www.owasp.org/index.php/Secure_Coding_Practices_in_C_and_C%2B%2B', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\nContinuous Integration:\\n\\n1. https://www.atlassian.com/continuous-delivery/continuous-integration-tutorial-cpp', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.codecademy.com/learn/learn-python\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\nTemplate Metaprogramming:\\nhttps://www.fluentcpp.com/2017/05/08/template-metaprogramming-in-cpp-a-gentle-introduction/\\n\\nLambda Expressions:\\nhttps://www.learncpp.com/cpp-tutorial/lambda-expressions/\\n\\nMove Semantics:\\nhttps://www.learncpp.com/cpp-tutorial/move-semantics/\\n\\nSmart Pointers:\\nhttps://www.learncpp.com/cpp-tutorial/smart-pointers/\\n\\nBoost Library:\\nhttps://www.boost.org/', '\\n\\n1. HTML: \\nhttps://www.w3schools.com/html/\\n\\n2. CSS: \\nhttps://www.w3schools.com/css/\\n\\n3. JavaScript: \\nhttps://www.w3schools.com/js/\\n\\n4. Python: \\nhttps://www.learnpython.org/\\n\\n5. Java: \\nhttps://www.tutorialspoint.com/java/index.htm', '\\n\\nC++: \\n1. https://www.learncpp.com/ \\n\\nBackend Development: \\n1. https://www.tutorialspoint.com/backend_development/index.htm']


